server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_manage_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
mybatis-plus:
  type-aliases-package: cn.cbr.usermanagesystem.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
sa-token:
  token-name: satoken
  timeout: 1800
  active-timeout: -1
  is-concurrent: false
  token-style: uuid
  is-log: false
  redis-template: true
